# Define the goal
float64 x                       # x coordinate of clicked point in image coords
float64 y                       # y coordinate of clicked point in image coords
int16 imageWidth                # width of image in pixels
int16 imageHeight               # height of image in pixels
---
# Define the result
bool success                    # true if 3D point could be found from image click point
---
# Define a feedback message
string message                  # text feedback
